### ISSUE TITLE
Variable in watch list not updating after breakpoint

### ISSUE THREAD

**Issue by ErnestoELC** [arduino/arduino-ide#412] opened 2021-06-11 13:27 UTC
### Describe the problem

When I type a variable to WATCH, I noticed that it doesn't get automatically updated after the execution stops on a breakpoint. So in order to display the updated value I need to double click in the variable and then click ok in the pop window.

https://user-images.githubusercontent.com/7290490/121692885-d6be5580-cac8-11eb-8cfb-2d974ea8649d.mp4

### To reproduce

1. Add variable counter to the watch list 
2. add a breakpoint at some pointer after the variable is increased in a loop
3. Start execution
4. On a variable, inspect the variable on the watch list

### Expected behavior

The variable should be updated after the execution is stopped in the breakpoint

### Arduino IDE version

2.0.0-beta.7

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-12-02 16:03
This bug has been resolved. I believe it was resolved by https://github.com/arduino/arduino-ide/pull/1706.

The reason I am not certain is because another bug (or perhaps another manifestation of this bug) made it impossible to start the debugger when a watch expression was set (https://github.com/arduino/arduino-ide/issues/1582). That bug was introduced at https://github.com/arduino/arduino-ide/commit/112153fb965f63d952d126c8244cd3f84f0a1a1b. I can still reproduce https://github.com/arduino/arduino-ide/issues/412 up to the commit before that one (69ac1f4), so I am at least certain it was not fixed before the introduction of https://github.com/arduino/arduino-ide/issues/1582.

**Closed by per1234** 2022-12-02 16:03 UTC
Labels: topic: code, type: imperfection, topic: debugger
