### ISSUE TITLE
IDE hangs when opening new file

### ISSUE THREAD

**Issue by ekaggrat** [arduino/arduino-ide#2247] opened 2023-10-06 01:58 UTC
### Describe the problem

The IDE starts up and when I try to open a new file there is only a main page with a heart beat icon.

### To reproduce

Start IDE and open new file.

### Expected behavior

New file should open.

### Arduino IDE version

2.2.1/2.2.2 nightly

### Operating system

Windows

### Operating system version

10

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2023-10-06 02:56
Hi @ekaggrat.

Please provide a detailed set of instructions I can follow to reproduce the problem. There are several different procedures that could be described as "open new file" so the instructions you provided are not sufficient.

I need to know exactly what I should do at each step. Don't leave anything out no matter how obvious it might seem to you.

**Comment by per1234** [comment] 2023-10-06 02:59
I see now this is a duplicate of https://github.com/arduino/arduino-ide/issues/2227

@ekaggrat this is very disrespectful behavior. Please only submit one report for each bug. Submitting duplicate reports is counterproductive because it means we spend time cleaning up your mess that could have been put towards actually investigating and fixing the bug.

**Closed by per1234** 2023-10-06 02:59 UTC
Labels: topic: code, status: waiting for information, type: imperfection
