### ISSUE TITLE
Serial Monitor - Copy does only work with limitations

### ISSUE THREAD

**Issue by SaKiEQ** [arduino/arduino-ide#2568] opened 2024-11-18 12:04 UTC
### Describe the problem

Copying text from Serial Monitor is limited to around the size the current screen shows. 
That alone would be an issue, but since the monitor can not be undocked, or opened in a stand
alone screen, only few lines are visible at best. 

### To reproduce

Just copy text from serial monitor to reproduce. 

### Expected behavior

In IDE 1, the entire serial monitor would be selected and copied. Which is very useful to debug some more complex 
problems, specially when board specific debugging information is display (that can be very detailed). 
Also IDE 1 allowed for a separate window, which in my case 'lives' on its on second screen, so I can reference debug output 
to code. 
The current state is miserable at best. Since I can neither have a full screen view (without loosing code window), not can I copy paste to an
external editor. 

### Arduino IDE version

2.3.3

### Operating system

macOS

### Operating system version

15.2 Beta (24C5079e)

### Additional context

This issue has been reported for over a year now. I don't thinks its a highly complex issue to address. 
Yet it does not seem to get any attention nor priority, which is sad. Since the key benefits of IDE 2 over 1 
is better UI. 

### Issue checklist

- [x] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [x] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [x] My report contains all necessary details

**Comment by per1234** [comment] 2024-11-18 13:32
Closing as duplicate of https://github.com/arduino/arduino-ide/issues/1081.

@SaKiEQ please don't submit duplicate issues. I understand you are frustrated by the fact that this long standing and impactful bug has not been fixed, but submitting duplicate issues actually makes it less likely for it to be resolved because it wastes the very limited resources Arduino has to dedicate to this project. Those wasted resources could instead be used productively on things like fixing Serial Monitor.

**Closed by per1234** 2024-11-18 13:32 UTC
Labels: type: imperfection
