### ISSUE TITLE
.ino Files unable to open

### ISSUE THREAD

**Issue by JustAProgrammerr** [arduino/arduino-ide#186] opened 2021-03-08 16:47 UTC
**Describe the bug**

I can't open my .ino files.  When I click "open with" it's just an alternative for the boot up for the IDE not literally opening that specific .ino file, I have to always CTRL+O from the IDE just to open my files, not when I'm at my desktop opening a .ino file.

**To Reproduce**
1. Go to Desktop
2. Click on .ino files
3. See error

**Expected behavior**

To open files like the earlier, non-problematic version of the IDE

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Beta 2.0.0

**Additional context**

Still has a good amount of features, and I love the new design, much better than the old versions.

**Comment by ubidefeo** [comment] 2021-03-08 19:41
hi @JustAProgrammerr 
this issue has already been reported and is being tracked as #72 
We have yet to implement OS file association

Thank you
u.

**Comment by ubidefeo** [comment] 2021-03-19 16:32
Closed as duplicate of #72

**Closed by ubidefeo** 2021-03-19 16:32 UTC
Labels: type: bug
