### ISSUE TITLE
Unable to scroll to bottom with long descriptions in Boards Manager

### ISSUE THREAD

**Issue by bergie5737** [arduino/arduino-ide#1944] opened 2023-03-09 11:47 UTC
### Describe the problem

When I open Boards Manager, under "Updatable" my first library is "esp32 by Espressif Systems Version 2.0.6" 
I am unable to scroll down enough to select "Install." I'm on full screen UHD, but cannot get to teh bottom.

### To reproduce

Open boards manager. If  "esp32 by Espressif Systems Version 2.0.6" is installed, you cannot scroll all the way down.

### Expected behavior

To be able to select the install button.

### Arduino IDE version

2.0.4

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment] 2023-03-09 14:12
Thanks for taking the time and reporting the bug. We are aware of some UI issues—for example, https://github.com/arduino/arduino-ide/issues/1591.

There is a PR addressing a couple of defects: https://github.com/arduino/arduino-ide/pull/1927. Please try it and see if the problem is still present. Here is an excellent guide on how to help us with the beta testing: https://github.com/arduino/arduino-ide/blob/main/docs/contributor-guide/beta-testing.md

I close this one as a duplicate of #1591. If you disagree or the PR does not fix your problem, please ping me here, and I will reopen.

**Closed by kittaakos** 2023-03-09 14:12 UTC
Labels: type: imperfection
