### ISSUE TITLE
CTRL+W should not close the application, only the tab for the current editor tab

### ISSUE THREAD

**Issue by stodge** [arduino/arduino-ide#1232] opened 2022-07-20 12:35 UTC
### Describe the request

Other Windows and Linux applications use CTRL+W to close the current editor tab. I found it a bit jarring to see the Arduino IDE quit when I tried to close an editor tab I was no longer using. I would prefer to follow convention and use CTRL+Q, or the typical key combination on all platforms, to quit the IDE.

### Describe the current behavior

When I press CTRL+W, the IDE quits.

### Arduino IDE version

rc8

### Operating system

Windows

### Operating system version

10 Home 21H2 19044.1826

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details

**Comment by per1234** [comment] 2022-07-20 12:40
Closing as duplicate of https://github.com/arduino/arduino-ide/issues/275

**Closed by per1234** 2022-07-20 12:40 UTC
Labels: type: enhancement
