### ISSUE TITLE
File -> Open file browser popup opens in background

### ISSUE THREAD

**Issue by php4fan** [arduino/arduino-ide#2325] opened 2024-01-04 12:58 UTC
### Describe the problem

When I do "File -> Open", the file browser doesn't seem to open, nothing seems to happen, except that Arduino's icon in the Task Manager changes to some "X" icon and has a "+" on the bottom indicating that there's more than one window. When I click on the icon, then the file browser popup comes to the foreground, and so I find out that it did open, but was on the background.

### To reproduce

go to File -> Open

### Expected behavior

Arduino's icon in the task manager shouldn't change to a different icon. The "+" on the bottom might be expected (though most applications do something better: the main window gets greyed out while the file browser popup is visible, and it doesn't count as an additional window). 
And most importantly, the file browser popup that has been opened as a result of a direct user input, should immediately be visible, focused, and on the foreground.

![image](https://github.com/arduino/arduino-ide/assets/13969584/13ee7ec3-4dff-40fe-8fc4-44ca8fd9abc6)

### Arduino IDE version

2.2.1

### Operating system

Linux

### Operating system version

Manjaro Linux

### Additional context

I did _not_ verify the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds) because the nightly build isn't usable.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment] 2024-01-30 07:03
Closing as a duplicate of https://github.com/arduino/arduino-ide/issues/2344.

I know this issue has been opened before #2344, but the other one has a valuable screencast, and at least I can see what problems the users have.

**Closed by kittaakos** 2024-01-30 07:03 UTC
Labels: type: imperfection
