### ISSUE TITLE
IDE is non-functional if package index can't be loaded

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#1084] opened 2022-06-20 12:33 UTC
### Describe the problem

[Package indexes](https://arduino.github.io/arduino-cli/dev/package_index_json-specification/) are used by the Arduino Boards Manager system to track the [Arduino boards platforms](https://arduino.github.io/arduino-cli/dev/platform-specification/) that are available for installation.

These come from two types of sources:

- The official [primary package index](https://downloads.arduino.cc/packages/package_index.json)
- URLs specified by the user via the "**Additional Boards Manager URLs**" field of the IDE's "**Preferences**" dialog

The package indexes are downloaded from these URLs by Arduino IDE 2.x on startup.

🐛 Under the following conditions, the IDE is non-functional:

- A package index cannot be downloaded from its URL
- The package index is not already present in `directories.data`

### To reproduce

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Add the following to the "**Additional Boards Manager URLs**" field:
   ```text
   https://downloads.arduino.cc/packages/package_nonexistent_index.json
   ```
   **ⓘ** The issue is not specific to this URL. Any URL that does not provide a package index URL download can be used.
1. Click the <kbd>**OK**</kbd> button.
1. Select **File > Quit** from the Arduino IDE menus.
1. Start the Arduino IDE.
1. Open the "Board Selector" menus.
   🐛 No boards are shown.
1. Open the **Tools** menu.
   🐛 There is no "**Boards**" menu.
1. Open the "**Boards Manager**" view.
   🐛 The view is empty, not even showing the currently installed platforms.
1. Open the "**Library Manager**" view.
   🐛 The view is empty.

🐛 The only way for the user to identify the problem is searching through the logs.

### Expected behavior

Clearly communicate to the user that there was a problem with downloading the package index.

It would probably also make sense to retain general functionality of the Arduino IDE (though of course the Boards Manager functionality that relies on the missing package index in particular will not be available).

### Arduino IDE version

2.0.0-rc7-snapshot-a715da3

### Operating system

Windows

### Operating system version

10

### Additional context

I bisected the issue to https://github.com/arduino/arduino-ide/commit/4c55807392b3b724e2c5912280c621f9ed8db5e6 (does not occur with the build from https://github.com/arduino/arduino-ide/commit/cb50d3a70d1dc34d46bb1373f9aa4678f14f7133)

---

The logs contain the following:

```text
root ERROR Uncaught Exception:
root ERROR Error: 13 INTERNAL: Error downloading index 'https://downloads.arduino.cc/packages/package_nonexistent_index.json': Server responded with: 404 Not Found
    at Object.callErrorFromStatus (C:\ide 2\tip\48-a715da3\resources\app\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (C:\ide 2\tip\48-a715da3\resources\app\node_modules\@grpc\grpc-js\build\src\client.js:349:49)
    at Object.onReceiveStatus (C:\ide 2\tip\48-a715da3\resources\app\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:328:181)
    at C:\ide 2\tip\48-a715da3\resources\app\node_modules\@grpc\grpc-js\build\src\call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

---

Even though it is most likely to occur with package indexes provided by via the "**Additional Boards Manager URLs**" preference (whether by user error, no connection to Internet, or transient network outage on the server), it does also occur even with the primary package index so long as the conditions described previously are present.

---

Originally reported at https://github.com/arduino/arduino-ide/issues/1036#issuecomment-1152531289

I mistakenly claimed that issue had been fixed by https://github.com/arduino/arduino-ide/pull/1045 because I did not realize at that time that the package index's absence from `directories.data` was a required condition to reproduce it.

---

Related:

- https://forum.arduino.cc/t/arduino-2-0-0-rc-7-no-board-manager-or-library-manager/1004131/6
- https://forum.arduino.cc/t/ide-2-0-0-rc8-missing-tools-board-and-other-menus/1007606

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment] 2022-07-01 13:12
This will be partially fixed with #1132. A follow-up issue is here: https://github.com/arduino/arduino-cli/issues/1788

**Comment by per1234** [comment] 2022-07-06 23:55
Hi @Lorandil. There have been significant advancements since the 2.0.0-rc8 version of the Arduino IDE you are using. Please always test using [the latest nightly build](https://www.arduino.cc/en/software#nightly-builds) before submitting a report here on GitHub.

In this case, there is work in progress in a pull request to even further improve the handling of these URLs. The tester build from that pull request is the most advanced form of the Arduino IDE. Please give it a try and then tell us whether it solves your issue.

I'll provide instructions for how you can download the tester build:

1. Sign in to your [**GitHub**](https://github.com/) account.
   (GitHub only allows downloads of the tester builds when you are signed in.)
1. Open this page in your browser:
   <https://github.com/arduino/arduino-ide/pull/1132/checks>
1. From the list of workflow runs on the left side of the page, click on "**Arduino IDE**" (this is the build workflow).
1. From the "**Artifacts**" section of the page, click the download link for your operating system.
   **ⓘ** For example, if you are using Windows, use the "**Windows_X86-64_zip**" link.
1. Wait for the download to finish.
1. Extract or install the downloaded file as usual.

**Comment by Lorandil** [comment] 2022-07-07 19:58
Hi @per1234 ,

I tried the nightly from today and it didn't solve the problem for me.

**Comment by per1234** [comment] 2022-07-07 21:07
@Lorandil I think it will be better for us to continue this investigation over on the Arduino Forum. Please post in the dedicated category for Arduino IDE 2.x:

https://forum.arduino.cc/c/software/arduino-ide-2-0-beta/93

I'm certain to see your post over there.

**Comment by per1234** [comment] 2022-07-08 12:57
The issue was closed inadvertently during the merge of https://github.com/arduino/arduino-ide/pull/1132 due to a chance occurrence of a [GitHub issue closing keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue).

The IDE has been made much more resilient to failed package index downloads via https://github.com/arduino/arduino-ide/pull/1132, and also does an excellent job of communicating about such failures to the user via the notification system.

The IDE now works just as expected when following the instructions I provided above. There remains one case where a failed package index download produces unexpected behavior:

1. Select **File > Preferences...** from the Arduino IDE menus.
1. Add the following to the "**Additional Boards Manager URLs**" field:
   ```text
   https://downloads.arduino.cc/packages/package_nonexistent_index.json
   ```
1. Click the <kbd>**OK**</kbd> button.
1. Select **File > Quit** from the Arduino IDE menus.
1. Rename or delete (⚠ carefully!) the following folder:
   - Windows:
     ```text
     %LOCALAPPDATA%\Arduino15\
     ```
     (e.g., `C:\Users\<username>\AppData\Local\Arduino15\`)
   - Linux:
     ```text
     ~/.arduino15/
     ```
   - macOS:
     ```text
     ~/Library/Arduino15/
     ```
1. Start the Arduino IDE.

🐛 The IDE startup hangs at the splash screen

### Additional context

The IDE will start and function correctly if you close and then restart it.

**Comment by Lorandil** [comment] 2022-07-10 17:58
Hi all,
just a quick update: The problem is fixed for me with the nightly of 2022-07-10.

The working boards are there and an error message is displayed - which exposes the root cause of the problem:
There was a blank after the esp8266 board manager link. Removing the blank solved the issue completely.
I suggest left/right trimming blanks from the boardmanager URLs.

Thanks for fixing the problem!

**Comment by per1234** [comment] 2022-07-13 10:38
I'm glad you were able to find the problem @Lorandil

>There was a blank after the esp8266 board manager link. Removing the blank solved the issue completely.
I suggest left/right trimming blanks from the boardmanager URLs.

Thanks for your report.

I did some experimentation but was not ever able to reproduce the problem. Please provide detailed instructions I can follow to reproduce it.

**Closed** 2022-10-05 07:17 UTC
Labels: topic: code, type: imperfection, topic: CLI
