### ISSUE TITLE
Add WiFi101/WiFiNINA Firmware Upgrade tool

### ISSUE THREAD

**Issue by tigoe** [arduino/arduino-ide#273] opened 2021-03-25 10:52 UTC
The WiFi101/WiFiNINA Firmware upgrade tool is missing. Please add it.

**Comment by ubidefeo** [comment] 2021-03-25 23:50
@tigoe 
The firmware update workflow we currently use in the Arduino IDE is flawed to say the least.
At each release of a firmware a new release of the Java IDE is expected, and users often read they need the latest download, flash the firmware and end up with an older version than expected.
The Java IDE Nightly Build is the best place to go to get the latest firmware.

Tooling Team is going to work on a standalone tool, which in the future could possibly be integrated into the IDE 2.0, but that is yet to be decided.

We don't yet have a solution to allow tools to be developed and added, since an IDE extension API would required and tools should be distributed and installed somehow.

Anyway, this is part of the known issues, and as duplicate of #30 it will be closed 🙏🏼

**Closed by ubidefeo** 2021-03-25 23:50 UTC
Labels: type: enhancement
