### ISSUE TITLE
Serial port remains open after Serial Monitor is closed

### ISSUE THREAD

**Issue by sayzergithub** [arduino/arduino-ide#1420] opened 2022-09-11 15:04 UTC
### Describe the problem

Once the serial monitor is opened, and then closed later on, port stays open while IDE is running.

### To reproduce

1. Connect a board to your computer.
1. Select the board and port from the Arduino IDE menus.
1. Open Serial Monitor.
1. Close Serial Monitor.
1. Attempt to open the port in an external serial port monitor.

🐛 The external serial port monitor can not access the port.

### Expected behavior

The port is closed when Serial Monitor is closed.

### Arduino IDE version

2.0.0-rc9.4

### Operating system

Windows

### Operating system version

10

### Additional context

I am using an ESP32 board with Silicon Labs CP2102 USB-Serial port chip.

---

I also experience the problem of the port being reset when the IDE is closed as reported at https://github.com/arduino/arduino-ide/issues/1546, but it occurs even when I already closed Serial Monitor before closing the IDE.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-09-13 05:54
Hi @sayzergithub. Thanks for your report.

I did some experimentation but was not able to reproduce the issue.

>port stays open while IDE is running

What are you doing to determine that the port stays open?

>Connect a board.

Which specific board (or boards) have you encountered this issue with?

>Board resets.

What are you doing to determine that the board reset?

**Comment by sayzergithub** [comment] 2022-09-13 06:38
"What are you doing to determine that the port stays open?"
Using an external serial port monitor, it can not access the port.

"Which specific board (or boards) have you encountered this issue with?"
ESP32 with SILAB CP2102 USB-Serial port chip.

"What are you doing to determine that the board reset?"
Immediately after IDE is closed, ESP32 board restarts.

**Comment by per1234** [comment] 2022-09-14 03:09
Thanks for the clarifications. In order to progress with the investigation, I'm going to ask you to try an experiment and then report your results here.

Please try this:

1. Open the Windows "**Task Manager**":
   https://techcommunity.microsoft.com/t5/windows-11/how-to-run-task-manager-on-windows-11-6-ways/m-p/2701239
1. If it is not already in that mode, click the "**More details**" button at the bottom of the **Task Manager** window.
1. Select the "**Details**" tab in the **Task Manager** window.
1. Start the Arduino IDE.
1. Select the board and port for your ESP32.
1. Open **Serial Monitor**.
1. Switch to the **Task Manager** window.
1. Verify that you can see a process with the name "**serial-monitor.exe**".
1. Switch to the Arduino IDE window.
1. Close **Serial Monitor** in the Arduino IDE window.
1. Switch to the **Task Manager** window.

After following these instructions, do you still see a process with the name "**serial-monitor.exe**" in the Windows "**Task Manager**"?

**Comment by per1234** [comment] 2022-10-11 08:50
Hi @sayzergithub. Did you ever get around to trying the experiment I requested in my previous reply? If so, what was the result?

**Comment by sayzergithub** [comment] 2022-10-11 10:48
Hello,
I am having some health issues with my kidneys.
I will try your suggestion as soon as I am up and running again.:)



Thank you,


Ömer YILDIZ

MCU Embedded Systems Designer

IT Professional
+90 539 822 9258
linkedin<https://www.linkedin.com/in/omeryildizlinkedin/>


Doğanet Elektronik ve Bilişim Sis. San. Tic. Ltd. Şti.
Perpa Tic. Merk B Blok Kat 11 No 1589 Şişli-Istanbul
Tel&Fax: 0212 210 1160

________________________________

**Comment by per1234** [comment] 2023-09-28 05:31
Since we didn't receive any additional reports or the additional information needed to investigate, I'll close this issue. If anyone is experiencing this problem with the latest version of Arduino IDE, please comment here and we will continue with the investigation.

---

Note there is a confirmed bug that causes the equivalent problem with Serial Plotter. That is tracked in the dedicated issue https://github.com/arduino/arduino-ide/issues/1423

**Closed by per1234** 2023-09-28 05:31 UTC
Labels: topic: code, status: waiting for information, type: imperfection
