### ISSUE TITLE
New, Open and Example all opens new windows, not in tabs tabs. Tabs can't be closed..

### ISSUE THREAD

**Issue by SofiaEngvall** [arduino/arduino-ide#1555] opened 2022-10-12 10:50 UTC
### Describe the problem

New, Open and Example all opens new windows. The only way to open a tab is to select open tab in the ... menu and then a new file is created... but I can't even select where!? (Also there is no way to close these tabs!? This includes closing the program and selecting Close in the menu. The second I expected to close the current tab, not the whole program.) The new windows are identical to the first one except there is no output part of the window. 

To test the open functionality I added a new text file be right-clicking and noticed there is no Show all files * in the open dialogue!? Is this program in alpha stage? I see no information that it's not a finished program. I just downloaded the latest, what I expected to be stable, version. Can I help with the project?

Also I currently have two "open" dialogues open by mistake since there is no lock on this.
Also the default directory is not used for new files (AppData\Local\Temp\...) when doing Show Sketch Folder, not looking good. A question "Do you want to save your file" for example would be nice.

I also got an error message "Unable to watch for file changes in this large workspace..." It's two empty files, feels really silly.

### To reproduce

File, New or File, Open or File, Example...

### Expected behavior

Instead of a new windows being opened I expect a tab to be added (unless I specify that I want a new window or have selected an option in preferences to always open files in a new window but this would just be silly too).
I also expect to be able to close tabs both by right clicking them and clicking an X on the tab.

### Arduino IDE version

2.0.0 Date: 2022-09-14T07:06:37.759Z  (4 weeks ago) No update when checking

### Operating system

Windows

### Operating system version

10 21H2 19044.2006

### Additional context

This was really frustrating. I'm looking for a project to contribute to. Maybe this is the one?

I did check the nightly and the functionality is the same though since I'm not using a alpha/beta version but the normal download I should have assumed the knowledge level of a normal user = Just updating with the built in update function. If this is not an acceptable version to run it should NOT be on top of the list of downloads.

Maybe my **_actual bug report_** is that this version is top on the page https://www.arduino.cc/en/software and Arduino IDE 1.8.19 is under the heading Legacy IDE! This one does not seem finished enough to be recommended to people expecting a functional IDE, not spending their time doing workarounds and sending in bug reports. If you put 2.0.0 as a Beta you can choose to test this would be the expected behavior.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by SofiaEngvall** [comment] 2022-10-12 10:54
The expected behavior of a new tab is for it to have no name until it is saved.

**Comment by per1234** [comment] 2022-10-12 14:59
>New, Open and Example all opens new windows. The only way to open a tab is to select open tab in the ... menu and then a new file is created... but I can't even select where!? (Also there is no way to close these tabs!? This includes closing the program and selecting Close in the menu. The second I expected to close the current tab, not the whole program.)

This is by design. The Arduino IDE is a tool for developing sketches, so the sketch is the unit it works with. Each open sketch is contained in a dedicated Arduino IDE window.

This might seem unnecessary for those who are used to working with single file sketches. However, Arduino sketches may contain multiple files, all of which are compiled as a single program. That fact is communicated intuitively to the user by this design.

>The new windows are identical to the first one except there is no output part of the window.

The "**Output**" view opens on demand. It is closed by default. If you do a compilation, upload, or any other operation that produces console output it will open. 

> I added a new text file be right-clicking and noticed there is no Show all files * in the open dialogue!?

It is not clear to me what you mean by this. Please provide a detailed description.

>Is this program in alpha stage?

No. It is in the stable production stage of development.

>I currently have two "open" dialogues open by mistake since there is no lock on this.

This was fixed 3 weeks ago: https://github.com/arduino/arduino-ide/pull/1322

>Also the default directory is not used for new files (AppData\Local\Temp...) when doing Show Sketch Folder, not looking good.

That is the location of the sketch before you save it.

>A question "Do you want to save your file" for example would be nice.

I don't see that there is a need to make saving the sketch as a step in the **Show Sketch Folder** operation. The two things aren't inherently linked.

I often use this feature as a convenient way to access the files produced by **Sketch > Export Compiled Binary**. I sometimes use this feature with a quick throwaway sketch. In this case, it would be inconvenient for me to have to go through a dialog just to access the binary file.

>I also got an error message "Unable to watch for file changes in this large workspace..." It's two empty files, feels really silly.

Again, you are using an outdated version of the IDE. This bug was fixed a month ago: https://github.com/arduino/arduino-ide/pull/1409

>Can I help with the project?

Contributions are welcome. Thanks! Please see the Contributor Guide to learn about the ways you can help:

https://github.com/arduino/arduino-ide/blob/main/docs/CONTRIBUTING.md#contributor-guide

I have a few specific suggestions for you:

Create a separate issue for each defect or potential enhancement you would like to report. You touch many unrelated subjects here. This type of issue is very difficult for us to manage. It is easy for us to miss one of the item and so this approach makes it less likely that all the things you report will be resolved.

Take a more positive and professional tone. Some of the wording used in this issue is very insulting. That is counterproductive.

Always test using the latest nightly build. You said you tried the nightly, but some of the bugs you reported do not occur when using the nightly build.

**Closed by per1234** 2022-10-12 14:59 UTC
Labels: type: imperfection

**Comment by SofiaEngvall** [comment] 2022-10-12 18:02
> > New, Open and Example all opens new windows. The only way to open a tab is to select open tab in the ... menu and then a new file is created... but I can't even select where!? (Also there is no way to close these tabs!? This includes closing the program and selecting Close in the menu. The second I expected to close the current tab, not the whole program.)
> 
> This is by design. The Arduino IDE is a tool for developing sketches, so the sketch is the unit it works with. Each open sketch is contained in a dedicated Arduino IDE window.
> 
> This might seem unnecessary for those who are used to working with single file sketches. However, Arduino sketches may contain multiple files, all of which are compiled as a single program. That fact is communicated intuitively to the user by this design.

Should I just give up and go back to Atmel studio instead? This is probable a no-go for me. Please, at least add an option in the preferences <3 Is it also intended not to be able to close tabs?

Also, I wanted to add a file in the current project by selecting new, not a new project. I wanted what you get from selecting New tab from the three dots menu in line with the tabs.

When pressing Examples/Open there was just an empty file open. Nothing I had opened or edited. I just started the program for the first time. I guess this is the default? You can't open it with no files? I assume it can't be open without a file as I can't close the files?

I've used computers and programmed since about 1985 and have worked as a IT specialist for a lot of years. I feel I'm not the worst at using programs and figuring out their gui's. This doesn't feel like it follows conventions so it's really hard to find what you're looking for. For example: What does new and close in the menu mean? By changing "New" to "New project" and "Close" to "Close application/all files" it would be more clear. You could then add a "New tab/file in project" doing the same as the three dots menu one (and my concerns would be met/this bug solved for real). If you want I could work with you on the gui.

> > The new windows are identical to the first one except there is no output part of the window.
> 
> The "**Output**" view opens on demand. It is closed by default. If you do a compilation, upload, or any other operation that produces console output it will open.

I want to have it always open and found no option for this. I hope there is one. If not it would be great if a toggle-button/option for this could be added. This would not be hard.

> > I added a new text file by right-clicking and noticed there is no Show all files * in the open dialogue!?
> 
> It is not clear to me what you mean by this. Please provide a detailed description.

Clicking the three dots in line with the tab(s) and select New Tab.
In the open dialog only specific extensions are visible. I added a file by right-clicking and was going to rename it to the right extension but had to type * in the file to open field. This is not standard feel either.

> > Is this program in alpha stage?
> 
> No. It is in the stable production stage of development.

That was not a question. I just don't feel the program is finished. I see that you didn't answer the most important part, the "Additional context". That's where I explain.

> > I currently have two "open" dialogues open by mistake since there is no lock on this.
> 
> This was fixed 3 weeks ago: #1322

Then why not update the buggy version on the web page? This is the point, the bug I'm reporting.

> > Also the default directory is not used for new files (AppData\Local\Temp...) when doing Show Sketch Folder, not looking good.
> 
> That is the location of the sketch before you save it.
> 
> > A question "Do you want to save your file" for example would be nice.
> 
> I don't see that there is a need to make saving the sketch as a step in the **Show Sketch Folder** operation. The two things aren't inherently linked.

This was a suggestion to get around the ugly behavior of showing a temp dir to a user.

> I often use this feature as a convenient way to access the files produced by **Sketch > Export Compiled Binary**. I sometimes use this feature with a quick throwaway sketch. In this case, it would be inconvenient for me to have to go through a dialog just to access the binary file.

You don't actually save the file before creating a binary?

> > I also got an error message "Unable to watch for file changes in this large workspace..." It's two empty files, feels really silly.
> 
> Again, you are using an outdated version of the IDE. This bug was fixed a month ago: #1409

Great, please update the web download and the integrated update tool update.

> > Can I help with the project?
> 
> Contributions are welcome. Thanks! Please see the Contributor Guide to learn about the ways you can help:
> 
> https://github.com/arduino/arduino-ide/blob/main/docs/CONTRIBUTING.md#contributor-guide

Thanks, I cloned it and read the docs and a bit on the theia web, curious to learn more about why it works as it does.

> I have a few specific suggestions for you:
> 
> Create a separate issue for each defect or potential enhancement you would like to report. You touch many unrelated subjects here. This type of issue is very difficult for us to manage. It is easy for us to miss one of the item and so this approach makes it less likely that all the things you report will be resolved.

I know it got a bit clumped but as mentioned above the true bug was in the additional context. I will try to do better if I ever make another one.

> Take a more positive and professional tone. Some of the wording used in this issue is very insulting. That is counterproductive.

I'm sorry if my frustration with installing a tool that didn't work (as I expected it to at least) leaked through. It is intended as constructive criticism.

Please tell me what you feel is insulting? That it's not ready to be released? How could I express this opinion without telling you? I truly feel it should be removed from the arduino site until basic bugs like the first one I commented on (Examples listing not showing examples) are fixed. I also feel this bug which you say is by design is on that level. This is my positive (to avoid user frustration and negativity towards arduino) and professional opinion.

I understand that you're working hard on it and that's great. I hope it will soon work in a good way.

> Always test using the latest nightly build. You said you tried the nightly, but some of the bugs you reported do not occur when using the nightly build.

I just tried the headline bug in the nightly and as I said I feel this was counterproductive due to this version being four weeks newer than the recommended advertised as stable version on the download page as linked above. Please update this one to save frustration for future downloaders, thank you! <3

If you want I can add these small things as separate suggestions/bugs. And I can help if you want. Or I can drop it. You decide :)

**Comment by BloodyRain2k** [comment] 2023-12-10 22:52
> This is by design. The Arduino IDE is a tool for developing sketches, so the sketch is the unit it works with. Each open sketch is contained in a dedicated Arduino IDE window.
> This might seem unnecessary for those who are used to working with single file sketches. However, Arduino sketches may contain multiple files, all of which are compiled as a single program. That fact is communicated intuitively to the user by this design.

I'm with Sofia on this one... It's *not* intuitive at all.
I didn't even know that this is the entire point of the IDE being "annoying", until finding this issue from googling for an option to stop the IDE from being annoying...
I genuinely thought that it's doing that just to be annoying, based on how everything else that has tabs works these days.

Though maybe that's on me and not knowing that "Sketch" means more along the lines of "Project".
Although I'd then argue that the latter definitely suggests more likely "something that has multiple files", which "sketch" definitely doesn't to me.
Quite the opposite even, "sketch" sounds more like a "make one and toss it away" thing, which I'd primarily see as a single file thing.

As for the UI, I think it would have been more intuitive to go for a semi-VSCode like approach, where each "sketch" gets it's own group of tabs and the sidepanel could just show the currently open sketches to switch between them.
Like how VSCode can have multiple folders open. Each "folder" would be a sketch and each "file" in that "folder" would be a tab, and depending on which sketch you have active, you get it's tabs.
That'd offer an option to avoid constantly opening a new 1 tab window for *everything* and this could actually suggest that there's a reason behind there being tabs but not being used "normally".

And for what it's worth, I also agree on the suggestion for a single-file focused usage option.
