### ISSUE TITLE
Error installing and including libraries into IDE 2.0.1

### ISSUE THREAD

**Issue by ProfSchneider** [arduino/arduino-ide#1609] opened 2022-11-01 06:51 UTC
### Describe the problem

I want to include a sort algorithm into IDE 2.0.1. First I found "QuickSortLib" in the Library Manager, installed 1.2.0 but found no example under examples. I opened the example QuickSortInt.ino and compiling led to the error:

```text
D:\SVN\AlphaBot\Demos\Arduino\libraries\QuickSortLib\examples\QuickSortInt\QuickSortInt.ino: In function 'void setup()':
D:\SVN\AlphaBot\Demos\Arduino\libraries\QuickSortLib\examples\QuickSortInt\QuickSortInt.ino:30:2: error: 'template<class T> class QuickSort' used without template parameters
  QuickSort::SortAscending(values100, 0, values100Length - 1);
  ^~~~~~~~~

exit status 1

Compilation error: 'template<class T> class QuickSort' used without template parameters
```

Then I included `ArduinoSort.zip` (via **Sketch > Include Library > Add .ZIP Library...**)
Result: no example, I opened a new sketch and inserted `#include <ArduinoSort.h>`
Error:

```text
Der Sketch verwendet 444 Bytes (1%) des Programmspeicherplatzes. Das Maximum sind 32256 Bytes.
Globale Variablen verwenden 9 Bytes (0%) des dynamischen Speichers, 2039 Bytes für lokale Variablen verbleiben. Das Maximum sind 2048 Bytes.
grpc: error while marshaling: string field contains invalid UTF-8

Compilation error: grpc: error while marshaling: string field contains invalid UTF-8
```

I did the same in IDE 1.8.19 and everything works fine.
How can I use librarys in IDE 2.0.1

### To reproduce

1. Install QuickSortLib via manager
2. Check examples
3. run demo

1. install ArduinoSort.zip (https://github.com/emilv/ArduinoSort)
2. Check examples
3. run demo

### Expected behavior

Serial output of SortArray.ino:

```text
Not sorted:
3
1
4711
2
0
sortArray:
0
1
2
3
4711
sortArrayReverse:
4711
3
2
1
0
Largest: 4711
Done! Sleep and repeat...
```

### Arduino IDE version

2.0.1

### Operating system

Windows

### Operating system version

10

### Additional context

Arduino Uno

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-11-01 08:12
Hi @ProfSchneider. You are reporting multiple unrelated problems here:

> I found "QuickSortLib" in the Library Manager, installed 1.2.0 but found no example under examples

I wasn't able to reproduce this, but there is a known bug where the examples menu is intermittently not populated: https://github.com/arduino/arduino-ide/issues/262

I'll provide instructions for the workaround:

1. Select **File > Quit** from the Arduino IDE menus.
1. Start Arduino IDE.

You should now find that the library's examples are listed under the **File > Examples > QuickSortLib** menu.

---

> ```text
> D:\SVN\AlphaBot\Demos\Arduino\libraries\QuickSortLib\examples\QuickSortInt\QuickSortInt.ino:30:2: error: 'template<class T> class QuickSort' used without template parameters
>   QuickSort::SortAscending(values100, 0, values100Length - 1);
>   ^~~~~~~~~
> ```

This is caused by a change the author of the "QuickSortLib" library made evidently with the intent of using the ["class template argument deduction" feature](https://en.cppreference.com/w/cpp/language/class_template_argument_deduction) added in the C++17 standard:

https://github.com/luisllamasbinaburo/Arduino-QuickSort/commit/b267f1fd138008ecd4f1eef7cb6673df55b91344

The "Arduino AVR Boards" platform of the Uno uses the C++11 standard, so it is expected that any code using the feature will fail to compile. That will happen no matter which version of the Arduino IDE you are using to compile the code.

A pull request was been submitted to revert that change so that the examples will compile once more:

https://github.com/luisllamasbinaburo/Arduino-QuickSort/pull/2

However, since it has not received any attention from the library author in over two years, you should not hope too much for it to be accepted anytime soon. Fortunately, the fix is trivial so you can simply apply it to the example sketch yourself:

https://github.com/luisllamasbinaburo/Arduino-QuickSort/pull/2/files#diff-955ad4d68e6cdfafc71f3308e6ff9549860139fee7422d8b31eb9bdf42273877R40

```cpp
QuickSort<int>::SortAscending(values100, 0, values100Length - 1);
```

So we can see this is not a problem with Arduino IDE 2.x, but instead a problem with the library.

---

> I included ArduinoSort.zip (via Sketch > Include Library > Add .ZIP Library...)
> Result: no example,

This is a known bug: https://github.com/arduino/arduino-ide/issues/659

I'll provide instructions for the workaround:

1. Select **File > Quit** from the Arduino IDE menus.
1. Start Arduino IDE.

You should now find that the library's example is listed under the **File > Examples > ArduinoSort** menu.

---

> ```text
> grpc: error while marshaling: string field contains invalid UTF-8
>
> Compilation error: grpc: error while marshaling: string field contains invalid UTF-8
> ```

This is a bug in Arduino IDE 2.x and/or Arduino CLI: https://github.com/arduino/arduino-cli/issues/1907

I will provide you with instructions for the workaround:

1. Select **File > Preferences** from the Arduino IDE menus.
1. Note the path shown in the "**Sketchbook location**" field.
1. Find the folder that contains the installation of the "ArduinoSort" library. It will be under the `libraries` subfolder of the sketchbook path.
1. Open the `library.properties` file you find there in any text editor.
1. Change line 4 of that file from this:
   ```text
   maintainer=Emil Vikstr�m
   ```
   to this:
   ```text
   maintainer=Emil Vikstrom
   ```
1. Save the file.

You should now be able to compile sketches using library without getting that "`grpc: error while marshaling: string field contains invalid UTF-8`" error.

---

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the previous issues about the defects you encountered.

If you end up with additional information to share, feel free to comment in the other threads.

**Closed by per1234** 2022-11-01 08:12 UTC
Labels: type: imperfection
