### ISSUE TITLE
Arduino IDE 2 not program MCUs Atmel and Arduino IDE 1.8.13 program

### ISSUE THREAD

**Issue by JorgeTorres01** [arduino/arduino-ide#1323] opened 2022-08-15 16:26 UTC
Hi,

I'm trying to program Atmel (microchip) MCUs with Arduino IDE. In IDE 1.8.13 its works but with the new IDE version (2.0.0-rc9.2) not program the MCU.

MCU: Attiny406
Board: megaTinyCore, version 2.5.11
Programmer: PICkit4

In IDE 2, when it tries to upload, it shows "using programmer : arduino":
![image](https://user-images.githubusercontent.com/10577951/184672606-deba4081-2a1f-4a0d-8fac-5e2f8aa95cf8.png)

But with IDE 1.8.13 its show: "using programmer : pickit4_updi":
![image](https://user-images.githubusercontent.com/10577951/184673203-b4338e31-a983-4e7a-9f70-db51954fc1ee.png)

In both IDEs I defined the PICkit4 programmer:
![image](https://user-images.githubusercontent.com/10577951/184673516-9a60e678-1c4c-4677-8bff-9a27dc1ecb6f.png)

I suppose that the IDE 2 to not program is due to it trying to use the programmer "arduino" instead "PICkit4"...
But this can be a bug of IDE 2 or a bug of board (megaTinyCore)? (or some mistake of mine? :) )
And how can this be resolved?

Thank you,
Jorge

**Comment by JorgeTorres01** [comment] 2022-08-15 21:01
I found in megaTinyCore GitHub that this board is not supported in IDE 2.0 yet : [megaTinyCore GitHub](https://github.com/SpenceKonde/megaTinyCore#warning-ide-20x-unsupported-and-all-versions-prior-to-200-rc92-known-to-have-critical-regressions)

This issue can be closed

Thank you

**Comment by per1234** [comment] 2022-08-18 05:10
Hi @JorgeTorres01. Thanks for taking the time to submit an issue.

### re: Incorrect programmer used when uploading

The problem is that you have selected a different board in the Arduino IDE 2.x than in Arduino IDE 1.x. The **megaTinyCore** boards platform has two different boards for the ATtiny406:

- **ATtiny3226/3216/1626/1616/1606/826/816/806/426/416/406**
- **ATtiny3216/1616/1606/816/806/416/406 w/Optiboot**

Since the latter board definition is specifically for use with the Optiboot serial bootloader, it does not support the "Upload Using Programmer" approach with the "PICkit4" programmer as you were expecting. If you select **Tools > Board > megaTinyCore > ATtiny3216/1616/1606/816/806/416/406 w/Optiboot** in Arduino IDE 1.x, you will get that same upload output with the "arduino" programmer type.

So you must make sure to select **Tools > Board > megaTinyCore > ATtiny3226/3216/1626/1616/1606/826/816/806/426/416/406** in either version of the IDE if you want to upload to your ATtiny406 using the "PICkit4" programmer.

### re: "Upload" vs "Upload Using Programmer" 

There is one difference in Arduino IDE 2.x that you should be aware of when using it with this board: 

Arduino IDE 1.x has [a convenience feature](https://arduino.github.io/arduino-cli/dev/platform-specification/#upload-using-programmer-by-default) for boards like this that don't have a normal upload capability where it will trigger an "**Upload Using Programmer**" operation when the user clicks the **Upload** button or selects **Sketch > Upload**.

Arduino IDE 2.x does not currently have that feature (tracked here: https://github.com/arduino/arduino-ide/issues/103). So you must select **Sketch > Upload Using Programmer** in order to upload to your ATtiny406 using the "PICkit4" programmer.

### re: "Unsupported"

Other than that missing convenience feature, Arduino IDE 2.x should work fine with your ATtiny406 and any other megaTinyCore boards.

The two serious bugs that resulted in [that notice in the **megaTinyCore** readme](https://github.com/SpenceKonde/megaTinyCore#warning-ide-20x-unsupported-and-all-versions-prior-to-200-rc92-known-to-have-critical-regressions) were fixed in Arduino IDE 2.0.0-rc9.2:

- https://github.com/arduino/arduino-cli/pull/1820
- https://github.com/arduino/arduino-cli/pull/1830

(they were actually bugs in Arduino CLI that also affected Arduino IDE users)

The "unsupported" in the **megaTinyCore** means that [**SpenceKonde**](https://github.com/SpenceKonde) will not provide support to those using **megaTinyCore** with Arduino IDE 2.x, but the Arduino IDE 2.x development team welcomes testing of the IDE with those boards.

Please do let us know if you find any problems with the IDE or identify possible enhancements. In addition to formal reports here on GitHub, feedback, support requests, or general discussion is welcome in the dedicated category of the Arduino Forum:

https://forum.arduino.cc/c/software/arduino-ide-2-0-beta/93

---

Since my testing indicates that everything should work as expected once the correct board is selected, I will close this as resolved.

**Closed by per1234** 2022-08-18 05:10 UTC
Labels: type: imperfection
