### ISSUE TITLE
Incorrect tab color in the settings dialog

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1179] opened 2022-07-13 12:09 UTC
### Describe the problem

When I have the dark theme active, I want to see the editor tab as dark in the settings dialog.

![Screen Shot 2022-07-13 at 14 06 34](https://user-images.githubusercontent.com/1405703/178730250-20e68b4b-cf82-4210-8f5e-06d426f1e37f.png)

### To reproduce

 - Open IDE2,
 - Select a dark theme,
 - Open the settings

### Expected behavior

If the theme is dark, the editor tab is not light.

### Arduino IDE version

b50bf427

### Operating system

macOS

### Operating system version

12.3.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-07-19 14:37
Closing as duplicate of https://github.com/arduino/arduino-ide/issues/1224

**Closed by per1234** 2022-07-19 14:37 UTC
Labels: topic: code, type: imperfection, topic: theme
