### ISSUE TITLE
I can't copy full text from Seril Monitor window

### ISSUE THREAD

**Issue by tankist-git-2** [arduino/arduino-ide#2520] opened 2024-09-27 12:34 UTC
### Describe the problem

It is often necessary to copy text from Serial Monitor window of Arduino IDE to analyze it later. But it is almost impossible to do.

### To reproduce

When I use Ctrl+A combination (Serial Monitor window in focus) code text is selected only (no selection on Serial Monitor window). When I try to select the text with a mouse there is another trouble: while scrolling during selection the part of selected text unselected itself.

### Expected behavior

When Serial Monitor window in focus, Ctrl+A combination should select text exactly in Serial Monitor window. When I select the text by mouse with scrolling, the selection should remains for full length of the window.

### Arduino IDE version

2.3.3

### Operating system

Windows

### Operating system version

Windows 10 22H2

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2024-09-27 17:02
Hi @tankist-git-2. Thanks for taking the time to submit an issue.

I see we already have previous reports about this:

> When I use Ctrl+A combination (Serial Monitor window in focus) code text is selected only (no selection on Serial Monitor window).

Duplicate of https://github.com/arduino/arduino-ide/issues/812

> When I try to select the text with a mouse there is another trouble: while scrolling during selection the part of selected text unselected itself.

Duplicate of https://github.com/arduino/arduino-ide/issues/1081

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the others.

In the future, please take the time to search the issue tracker for existing issues before submitting one. Thanks in advance for your cooperation.

**Closed by per1234** 2024-09-27 17:02 UTC
Labels: topic: code, type: imperfection, topic: serial monitor
