### ISSUE TITLE
Serial.println() is marked as an error when using Arduino Zero board

### ISSUE THREAD

**Issue by rsora** [arduino/arduino-ide#16] opened 2021-02-12 14:31 UTC
**Describe the bug**
This issues happens on Windows using the Arduino Zero board (Native Port), the function `Serial.println()` is marked as an error with the following message `No matching member function for call to 'println'`
But the sketch compiles correctly.

**To Reproduce**
1. Select Arduino Zero (Native USB Port)
2. Create the following sketch:
```
void setup() {
  // put your setup code here, to run once:
Serial.begin(9600);
}

void loop() {
  // put your main code here, to run repeatedly:
Serial.println("cicia");
}

```

**Expected behavior**
`Serial.println()` it shouldn't be marked as an error

**Screenshots**
![image](https://user-images.githubusercontent.com/35916119/107780610-325d1a00-6d47-11eb-80f3-45e81e856f27.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: 2.0.0-beta.1-snapshot.9e35571
- Date: 2021-02-12T08:28:48.914Z
- CLI Version: nightly-20210212 alpha [560025a6]

**Comment by per1234** [comment] 2021-11-03 13:58
Closing as duplicate of https://github.com/arduino/arduino-ide/issues/112

**Closed by per1234** 2021-11-03 13:58 UTC
Labels: type: imperfection, topic: language server, criticality: low
