### ISSUE TITLE
Files from outside of sketch are treated as read-only

### ISSUE THREAD

**Issue by marcinn** [arduino/arduino-ide#2507] opened 2024-09-15 20:15 UTC
### Describe the problem

Who is this idiot who forbade me from editing the sources of my libraries? Thank you.

### To reproduce

1. Click on the include file of your lib
2. Try to edit it

### Expected behavior

Edit

### Arduino IDE version

2.3.2

### Operating system

Linux

### Operating system version

Linux 6.1.85-1-MANJARO

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2024-09-15 22:25
Closing as duplicate of https://github.com/arduino/arduino-ide/issues/743

@marcinn your issue has an unacceptably rude tone. If I see any further such conduct from you I will ban you from all of Arduino's repositories and report your account to GitHub.

**Closed by per1234** 2024-09-15 22:25 UTC
Labels: type: imperfection
