### ISSUE TITLE
No upload with Debugger possible 

### ISSUE THREAD

**Issue by Mnanfiodkfna** [arduino/arduino-ide#1756] opened 2022-12-09 01:00 UTC
### Describe the problem

The debugging of the sketch works perfect. Also the upload of changes while debugging after new start of the debug session  works also perfect.
But when I tried to upload a sketch with the SEGGER mini to a Arduino MKR WiFi 1010 board and got following error message:

```text
Globale Variablen verwenden 4152 Bytes (12%) des dynamischen Speichers, 28616 Bytes für lokale Variablen verbleiben. Das Maximum sind 32768 Bytes.
"/Users/martin/Library/Arduino15/packages/arduino/tools/openocd/0.10.0-arduino7/bin/openocd" -d2 -s "/Users/martin/Library/Arduino15/packages/arduino/tools/openocd/0.10.0-arduino7/share/openocd/scripts/" -f "interface/jlink.cfg" -c "set telnet_port 0" -c "transport select swd" -f "target/at91samdXX.cfg" -c "telnet_port disabled; program {/private/var/folders/_k/60_7r7sx7qn851y2vlynwtzm0000gn/T/arduino-sketch-A1425C61347C8E72A11EDC26CFD6D820/ADC_einlesen_V0.9.ino.hex} verify reset; shutdown"
Open On-Chip Debugger 0.10.0+dev-gf0767a31 (2018-06-11-13:48)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2
0
swd
none separate
adapter speed: 400 kHz
cortex_m reset_config sysresetreq
Error: Failed to claim interface: LIBUSB_ERROR_ACCESS.
Error: Failed to open device: unspecified error.
Error: No J-Link device found.
Error: No Valid JTAG Interface Configured.
Fehlgeschlagene Programmierung: Hochladefehler: exit status 255
```

### To reproduce

Sketch => Upload Using Programmer

### Expected behavior

I expected that the sketch will upload to the Arduino - board.
In a Beta- version of June 2022 it did work.

### Arduino IDE version

2.0.3

### Operating system

macOS

### Operating system version

MacOS Monterey 12.6.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-12-10 11:40
Hi @Mnanfiodkfna. This is not caused by a problem with Arduino IDE. If you run the same `openocd` command from the command line you'll surely get the same error:

```text
"/Users/martin/Library/Arduino15/packages/arduino/tools/openocd/0.10.0-arduino7/bin/openocd" -d2 -s "/Users/martin/Library/Arduino15/packages/arduino/tools/openocd/0.10.0-arduino7/share/openocd/scripts/" -f "interface/jlink.cfg" -c "set telnet_port 0" -c "transport select swd" -f "target/at91samdXX.cfg" -c "telnet_port disabled; program {/private/var/folders/_k/60_7r7sx7qn851y2vlynwtzm0000gn/T/arduino-sketch-A1425C61347C8E72A11EDC26CFD6D820/ADC_einlesen_V0.9.ino.hex} verify reset; shutdown"
```

So I'm going to close this as off topic for the Arduino IDE repository. You are welcome to request assistance over on the Arduino Forum:

https://forum.arduino.cc/

**Closed by per1234** 2022-12-10 11:40 UTC
Labels: type: imperfection
