### ISSUE TITLE
Fix dialogs UI scalability vol 2 - Unexpected dialog layouts

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-ide#1350] opened 2022-08-24 14:32 UTC
### Describe the problem

This is a follow-up of https://github.com/arduino/arduino-ide/pull/1311.

Several dialogs have an unexpected layout.
 - If the board name is long, the board select dialog is ugly
    ![Screenshot 2022-08-23 at 17 15 08](https://user-images.githubusercontent.com/1405703/186445095-5a728544-1cd6-4b09-95a8-f4c541dd956b.png)
 - The new file dialog is too small. Start typing and use an unsupported file extension. The dialog grows with the validation error message.
    <img width="248" alt="Screen Shot 2022-08-24 at 16 30 48" src="https://user-images.githubusercontent.com/1405703/186445358-43c671a0-40e5-4b31-956c-eed35a7d9194.png">
 

### To reproduce

See above

### Expected behavior

The dialogs look the same as before arduino/arduino-ide#1311

### Arduino IDE version

Version: 2.0.0-rc9.2.nightly-20220824 Date: 2022-08-24T03:48:57.272Z CLI Version: git-snapshot [04e70c53]  Copyright © 2022 Arduino SA

### Operating system

macOS

### Operating system version

12.5.1

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by ubidefeo** [comment] 2022-08-25 15:26
I have taken more screenshots since the size of this dialog changes as you type

<img width="1201" alt="CleanShot 2022-08-25 at 16 29 13@2x" src="https://user-images.githubusercontent.com/1894487/186705678-12c0517e-ef0f-4653-ab53-7e0ec184a578.png">

<img width="1204" alt="CleanShot 2022-08-25 at 16 29 32@2x" src="https://user-images.githubusercontent.com/1894487/186706300-f7b7abb6-c554-489b-a6bf-acaa6037d4e1.png">

<img width="1204" alt="CleanShot 2022-08-25 at 16 29 44@2x" src="https://user-images.githubusercontent.com/1894487/186706337-f911e486-195e-49f2-9380-724ecb8cabdf.png">

**Comment by Volt23** [comment] 2022-08-26 10:05
This and the Preferences dialog should have a fixed with of 640px, we have a min size window set to 680px, making this size safe when resizing the workspace.

**Comment by kittaakos** [comment] 2022-08-26 10:22
> new tab dialog

Why the new tab only? What about rename, etc.

**Comment by Volt23** [comment] 2022-08-29 07:30
@kittaakos 
All simple dialogs - with one input only - should be 480px fixed width. In this specific case of the tabs' contextual menu the dialogs are: New tab, Rename and Delete.

**Comment by kittaakos** [comment] 2022-08-30 13:03
Boards list is getting smaller as I filter.

https://user-images.githubusercontent.com/1405703/187443785-2d6c80f2-a6fd-4c32-8cc8-0e93e6128a89.mp4

**Comment by kittaakos** [comment] 2022-08-31 13:35
> Boards list is getting smaller as I filter.

The dialog and the internal port list also change when I toggle _Show all ports_:


https://user-images.githubusercontent.com/1405703/187691171-f49c1c59-eea3-4374-8c51-f5ab3c5e81a6.mp4

**Comment by per1234** [comment] 2022-09-16 04:14
### Describe the problem

Width of "**Enter additional URLs, one for each row**" field of "**Additional Boards Manager URLs**" dialog is not correctly sized relative to dialog width.

### To reproduce

1. Select **File > Preferences** from the Arduino IDE menus.
1. Click the button on the right side of the "**Additional Boards Manager URLs**" field.

🐛 There is an horizontal scrollbar under the "**Enter additional URLs, one for each row**" field.
🐛 The user must scroll the field horizontally in order to access the field resize control.

![additional-boards-manager-urls](https://user-images.githubusercontent.com/8572152/190555115-0c3e2d36-6840-4e7b-8a32-b8a49a7c47e3.gif)

### Arduino IDE version

2.0.0-rc9.3.snapshot-d8377e0 (tester build for https://github.com/arduino/arduino-ide/pull/1406/commits/51979205e6d11583c1dcbbe3f4d1c4dff6f53a33)

### Operating system

Windows 10

### Additional context

Originally reported at https://github.com/arduino/arduino-ide/issues/1444

---

Note also the ugly lack of spacing between the bottom of the scroll bar and the top of the dialog's buttons.

**Comment by kittaakos** [comment] 2022-09-16 06:59
> Width of "**Enter additional URLs, one for each row**" field of "**Additional Boards Manager URLs**" dialog is not correctly sized relative to dialog width.

See the fix here: https://github.com/arduino/arduino-ide/pull/1382#pullrequestreview-1108862635.

Note that this is a partial fix, as the left and the right border are missing from the `<textarea>`.

**Closed** 2022-09-20 12:36 UTC
Labels: topic: code, type: imperfection, criticality: medium
