### ISSUE TITLE
Auto Format function does not work

### ISSUE THREAD

**Issue by MicSG-dev** [arduino/arduino-ide#194] opened 2021-03-10 03:37 UTC
The Auto Format function, triggered by the shortcut CTRL + T or the Tools -> Auto Format menu, is not working. When triggering Auto Format, nothing happens to the code when it is badly formatted.

IDE Version:

> Version: 2.0.0-beta.3
Date: 2021-02-26T10:48:13.025Z
CLI Version: 0.16.1 alpha [76f55490]

**Comment by kittaakos** [comment] 2021-03-11 09:50
This issue a duplicate of https://github.com/arduino/arduino-ide/issues/83. Closing. @MicSG-dev, let me know if you disagree and I am happy to discuss it.

**Closed by kittaakos** 2021-03-11 09:50 UTC
Labels: conclusion: duplicate, topic: language server

**Comment by MicSG-dev** [comment] 2021-03-11 19:04
In [# 83] (https://github.com/arduino/arduino-ide/issues/83), it says that "Automatic formatting seems to work only on INO files; nothing happens when applied to h or cpp files". But my problem is that automatic formatting for INO files does not work.

I installed the arduino IDE 2.0 by zip.

**Comment by kittaakos** [comment] 2021-03-11 20:34
> In #83, it says that "Automatic formatting seems to work only on INO files; nothing happens when applied to h or cpp files". But my problem is that automatic formatting for INO files does not work.
> 
> I installed the arduino IDE 2.0 by zip.

Thanks for the feedback, you're right. I have linked the incorrect issue. Here is the correct one: https://github.com/arduino/arduino-ide/issues/78

**Comment by MicSG-dev** [comment] 2021-03-11 20:53
ok

**Comment by kittaakos** [comment] 2021-03-11 21:01
The fix will be part of the next beta release for sure. The [changes](https://github.com/arduino/arduino-language-server/pull/69) are all ready for the merge. Please bear with us. Thanks!

**Comment by MicSG-dev** [comment] 2021-03-11 21:29
Don't worry, take as much time as you need. I'm happy to help.
