### ISSUE TITLE
Add Serial Plotter 

### ISSUE THREAD

**Issue by tigoe** [arduino/arduino-ide#272] opened 2021-03-25 10:51 UTC
Please put the Serial Plotter back from IDE 1.0. It's very useful.

**Comment by ubidefeo** [comment] 2021-03-25 23:54
@tigoe 
we cannot bring that serial plotter inside this IDE, a redesign/implementation in web technologies is required.
It's in the roadmap and listed in the missing features in the Beta 3 release notes

>Serial Plotter (#54)
Proxy Auto detect (#29)
Teensy Support (#90)
Legacy tools (ESP exception decoder and others) (#58)
i18n internationalisation (#28)
Wifi101/WifiNINA Firmware update (#30)
MDNS discovery (#123)
Language server doesn't support boards of the "megaAVR" architecture (#31)

as a duplicate of #54 this issue will be closed

**Closed by ubidefeo** 2021-03-25 23:54 UTC
Labels: type: enhancement
