### ISSUE TITLE
code not uploding on windows 11 os

### ISSUE THREAD

**Issue by harish00506** [arduino/arduino-ide#2341] opened 2024-01-26 04:37 UTC
### Describe the problem

Sketch uses 922 bytes (2%) of program storage space. Maximum is 32256 bytes.
Global variables use 9 bytes (0%) of dynamic memory, leaving 2039 bytes for local variables. Maximum is 2048 bytes.
avrdude: ser_open(): can't set com-state for "\\.\COM3"
Failed uploading: uploading error: exit status 1

### To reproduce

just up load any program to the bord

### Expected behavior

don't know

### Arduino IDE version

arduino ide 2.2.1

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2024-01-26 05:11
Hi @harish00506. Thanks for your interest in this open source project. This error is caused by an incompatibility between the latest version of the driver for the WCH CH340 USB chip and certain sketchy CH340 chips found on low quality Chinese Arduino derivative boards.

The error is coming from the [**AVRDUDE** uploader tool](https://avrdudes.github.io/avrdude/) rather than Arduino IDE itself so there is nothing that could be done to fix it within the Arduino IDE codebase hosted in this repository.

So I will close this as off topic.

If you post over on Arduino Forum, we'll be happy to provide instructions you can follow to get your cheapo board working:

https://forum.arduino.cc/

**Closed by per1234** 2024-01-26 05:11 UTC
Labels: type: imperfection
