### ISSUE TITLE
Compiling for ESP32 fails: "Access is denied."

### ISSUE THREAD

**Issue by mjwright** [arduino/arduino-ide#2147] opened 2023-07-19 20:16 UTC
### Describe the problem

Compilation fails with "Access is denied" when Windows path contains a space in the user name (e.g., between firstname and lastname)

`cmd /c type nul > "C:\Users\firstname" "lastname\AppData\Local\Temp\arduino\sketches\BCC6D161902E6D97CFF1F1190C34FFBA/file_opts"`

See forum discussion [https://forum.arduino.cc/t/compiling-for-esp32-fails-access-is-denied](https://forum.arduino.cc/t/compiling-for-esp32-fails-access-is-denied)

### To reproduce

Compile a sketch located in Windows user folder where the username contains a space.

### Expected behavior

Compilation should succeed.

### Arduino IDE version

2.1.1

### Operating system

Windows

### Operating system version

11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2023-07-19 23:35
Hi @mjwright. This is caused by a bug in the esp32 boards platform, not by anything in the Arduino IDE codebase that is hosted in this repository so I'll close this as off topic.

There is already a fix in progress:
https://github.com/espressif/arduino-esp32/pull/8433

**Closed by per1234** 2023-07-19 23:35 UTC
Labels: type: imperfection
