### ISSUE TITLE
The popup menu to select board and port shows two ports selected

### ISSUE THREAD

**Issue by mahboud** [arduino/arduino-ide#1286] opened 2022-08-04 08:16 UTC
### Describe the problem

I expect only one board to be selected, not both. 

Trying to reselect the serial board does nothing. Trying to deselect the selected bluetooth port, makes the serial port above deselected. Next, selecting the serial port will then deselect the bluetooth port and select the serial port.

The menu will operate normally until I plug and unplug (or power cycle) the ESP32 board attached. The double selected menu returns.

 <img width="246" alt="image" src="https://user-images.githubusercontent.com/1689095/182796324-bf9c0d03-1277-4deb-beb9-2509a97afbf4.png">

### To reproduce

Close all the sketches. Quit Arduino. Open Arduino. My ESP32 isn't plugged in yet. I see:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/1689095/182798013-63471259-8835-44e0-9e8b-6071657d1832.png">

Then I plug my ESP32 in. I see:

<img width="245" alt="image" src="https://user-images.githubusercontent.com/1689095/182798120-07f9cac7-3dc2-4def-941a-b18b33a3cad3.png">

I select the top one. (I don't want ever to use the bluetooth port and don't know how I can get the IDE to ignore it and never select it!) This is what i see:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/1689095/182798296-e0568fd9-e286-46ea-ad78-7bab1a18c9ac.png">

### Expected behavior

This is what I expect:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/1689095/182798377-f394cd56-58ce-4675-a0b9-25f0110b9f86.png">

Preferably i wouldn't see the bluetooth option at all.

### Arduino IDE version

Version: 2.0.0-rc9.1-nightly-20220804 Date: 2022-08-04T03:30:39.630Z CLI Version: 0.25.1 [436f0bb9] 

### Operating system

macOS

### Operating system version

10.15.7

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-09-22 20:59
Thanks @mahboud. I see this is a duplicate of https://github.com/arduino/arduino-ide/issues/928, which was fixed by https://github.com/arduino/arduino-ide/pull/1328

If you haven't already, please give Arduino IDE 2.0.0 (or the nightly build if you would like to help out the project through beta testing) a try. The problem should no longer occur. The download links are listed here:

https://www.arduino.cc/en/software

**Closed by per1234** 2022-09-22 20:59 UTC
Labels: topic: code, type: imperfection
