### ISSUE TITLE
Serial Monitor: Autoscroll fails

### ISSUE THREAD

**Issue by rs0xFFFF** [arduino/arduino-ide#2016] opened 2023-04-13 21:58 UTC
### Describe the problem

In Serial Monitor it sometimes happens that the new logging line is not visible and remains hidden behind the blue status bar. You then have to drag the scrollbar down with a click. It's extremely annoying when you expect an output that's already there but doesn't see it.

### To reproduce

Write to Serial Monitor

### Expected behavior

see above

### Arduino IDE version

2.0.4

### Operating system

Windows

### Operating system version

Win11

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2023-04-14 04:42
Hi @rs0xFFFF. Thanks for your report.

>2.0.4

Some autoscroll-related bugs were fixed since the time of the 2.0.4 release you are using:

https://github.com/arduino/arduino-ide/pull/1928

Please try the nightly build of Arduino IDE and then comment here to let me know whether or not the bug still occurs. The nightly build download links are listed here:

https://www.arduino.cc/en/software#nightly-builds

**Comment by LuSeKa** [comment] 2023-04-22 05:07
I noticed this issue today in version 2.1.0 as well. I have not tried the latest nightly build yet.

**Comment by per1234** [comment] 2023-04-22 14:18
Hi @rs0xFFFF. Did you ever find the time to try the latest build of Arduino IDE? If so, does the bug still occur for you?

**Comment by per1234** [comment] 2023-04-22 14:26
Hi @LuSeKa. Thanks for your report. I did some experiments following the procedures that would produce the previously fixed scrolling-related bugs in older IDE versions:

- https://github.com/arduino/arduino-ide/issues/1602#issue-1428988065
- https://github.com/arduino/arduino-ide/issues/972#issue-1216506458
- https://github.com/arduino/arduino-ide/issues/1736#issue-1474595449
- https://github.com/arduino/arduino-ide/issues/1736#issuecomment-1359713467
- https://github.com/arduino/arduino-ide/issues/1724#issue-1470709413

None of those procedures produced any misbehavior for me when using Arduino IDE 2.1.0.

Please provide detailed instructions we can follow to reproduce the problem you encountered. You might be able to adapt one of the the instructions I linked above for that purpose.

Please also tell us which operating system you are using.

**Comment by rs0xFFFF** [comment] 2023-04-22 17:36
> Hi @rs0xFFFF. Did you ever find the time to try the latest build of Arduino IDE? If so, does the bug still occur for you?

Unfortunately, no. I'm back to 1.8 because I have an urgent project.

**Comment by per1234** [comment] 2023-09-28 05:34
I'll close this as resolved because we haven't received any other reports of such a problem since the fixes I mentioned in my previous comment.

I'm confident we would have received such reports because we were getting a lot of them during the times when the fault was occurring.

**Closed by per1234** 2023-09-28 05:34 UTC
Labels: topic: code, status: waiting for information, type: imperfection, topic: serial monitor
