### ISSUE TITLE
On font increase dark theme goes light in code editor

### ISSUE THREAD

**Issue by gfmoore** [arduino/arduino-ide#534] opened 2021-10-08 13:40 UTC
### Describe the problem

As title says.

### To reproduce

Not specified.

### Expected behavior

Font size change does not change the active theme.

### Arduino IDE version

2.0.0-beta.12

### Operating system

Windows

### Operating system version

Not specified

### Additional context

I was able to revert back to dark theme.

**Comment by per1234** [comment] 2023-06-19 17:10
I am able to reproduce the fault using the reported version Arduino IDE 2.0.0-beta.12 through 2.0.0-rc8 by the following procedure:

1. Select **File > Quit** from the Arduino IDE menus if it is running.
1. Rename or delete (:warning: cautiously) the following folders to effectively simulate the environment of a first run (in order to produce the conditions for https://github.com/arduino/arduino-ide/issues/530):
   - Windows:
     ```
     C:\Users\<username>\.arduinoIDE
     ```
     ```
     C:\Users\<user name>\AppData\Roaming\arduino-ide
     ```
   - Linux:
     ```
     ~/.arduinoIDE
     ```
     ```
     ~/.config/arduino-ide
     ```
   - macOS:
     ```
     ~/.arduinoIDE
     ```
     ```
     ~/Library/Application Support/arduino-ide
     ```
1. Start Arduino IDE.
   The IDE coloration is as we would expect when it is configured for the "**Dark (Theia)**" theme.
1. Select **Edit > Increase Font Size** from the Arduino IDE menus.

🐛 The IDE's theming changes to what we would expect when it is configured for the "**Light (Theia)**" theme.

I am not able to reproduce the fault with 2.0.0-rc9 so I will conclude this was fixed by https://github.com/arduino/arduino-ide/pull/1160

**Closed by per1234** 2023-06-19 17:10 UTC
Labels: priority: high, topic: code, type: imperfection, topic: theme, criticality: medium
