### ISSUE TITLE
Cosmetic suggestions for better work 

### ISSUE THREAD

**Issue by VladimirVecera** [arduino/arduino-ide#480] opened 2021-08-15 07:40 UTC
After hovering the mouse in the code at the library, string or anything else, a window will always appear in a very short time. Is it possible to display the window in a longer time, for example in 4 seconds? Currently, if I want to select the mouse code, before I click the mouse button, a window will pop up immediately. It can't be done. 
IMAGE: [https://ctrlv.cz/shots/2021/08/15/wv3D.png](url)

The library manager and board manager contains a filter that would show which modules I have installed and which modules need to be updated. There is only a search, which is not enough. 

When validating the code, the percentage of completion is not seen anywhere - the validation status. Is it possible to add? 

The selected arduino board contains orange pipe icons at the top. Can't the icon turn green when the board is connected?

**Comment by per1234** [comment] 2021-09-08 05:25
Hi @VladimirVecera. Thanks so much for your suggestions. In the future, please open a separate issue for each distinct suggestion. Multiple different suggestions clumped into a single issue are difficult to track.

>After hovering the mouse in the code at the library, string or anything else, a window will always appear in a very short time.

Duplicate of https://github.com/arduino/arduino-ide/issues/483. This one came first, but that one is a dedicated issue.

>Currently, if I want to select the mouse code, before I click the mouse button, a window will pop up immediately. It can't be done.

Duplicate of https://github.com/arduino/arduino-language-server/issues/68

>The library manager and board manager contains a filter that would show which modules I have installed and which modules need to be updated. There is only a search, which is not enough.

Duplicate of https://github.com/arduino/arduino-ide/issues/177

>The selected arduino board contains orange pipe icons at the top. Can't the icon turn green when the board is connected?

Duplicate of https://github.com/arduino/arduino-ide/issues/200

**Closed by per1234** 2021-09-08 05:25 UTC
Labels: type: enhancement
