### ISSUE TITLE
IDE should not quit on closing of last open sketch (workspace)

### ISSUE THREAD

**Issue by paschlie** [arduino/arduino-ide#91] opened 2020-09-12 17:35 UTC
- The App should not quit upon the closing of the last open editor window; instead it should open an open-project window, including an option to create a new project

If one considers the app's file menu; it really makes no sense to be forced to open a new file, prior to closing a currently open one; but if once the currently open file is closed, the app quits, then the file menu becomes inaccessible and can't be used to open another; which is not really a useful nor thereby a desirable behavior.

**Comment by kittaakos** [comment] 2022-09-15 07:16
Duplicate of #758.

I updated the other issue with the acceptance criteria and moved the conversation from here to [there](https://github.com/arduino/arduino-ide/issues/758#issuecomment-1247679940).

**Closed by kittaakos** 2022-09-15 07:16 UTC
Labels: type: enhancement, topic: code, os: macos
