### ISSUE TITLE
"Are you sure you want to close the sketch?" message when doing "Save as" with dirty sketch

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-ide#38] opened 2021-02-25 16:13 UTC
## Describe the bug

If a "Save As..." is done when the sketch is in an unsaved (AKA "dirty") state, the IDE presents an unexpected "**Are you sure you want to close the sketch?**" dialog.

Regardless of which choice the user selects in the dialog, the resulting sketch files do not contain the unsaved changes that were in the editor.

## To Reproduce

1. Select **File > Preferences** from the Arduino IDE menus.
1. Uncheck the box next to "**☐ Auto save**"
1. Click the <kbd>OK</kbd> button.
1. Select **File > New** from the Arduino IDE menus.
1. Make some change to the sketch and do not save.
1. Select **File > Save As...** from the Arduino IDE menus.
1. Click the <kbd>Save</kbd> button.
   An "Are you sure you want to close the sketch?" message is shown unexpectedly, since you did not do anything that would be considered a close operation.
1. Click the <kbd>Yes</kbd> button.
   The IDE window now closes.
1. Open the sketch you saved via the "Save As..." operation.
1. Check whether the change you made is present.
   It is not!
1. Select **File > Save As...** from the Arduino IDE menus.
1. Click the <kbd>Save</kbd> button.
   An "Are you sure you want to close the sketch?" message is shown unexpectedly, since you did not do anything that would be considered a close operation.
1. Click the <kbd>No</kbd> button.
1. Open the sketch you saved via the "Save As..." operation.
1. Check whether the change you made is present.
   It is not!

## Expected behavior

The exact contents of the sketch that is open in the editor are always saved to the sketch specified via the "Save As..." operation, regardless of dirty state.

No "**Are you sure you want to close the sketch?**" dialog is shown during this procedure.

The currently open sketch is replaced by the new sketch created by the "Save As..." process, just as it does after "Save As..." with a non-dirty sketch.

## Desktop

- OS: Windows 10
- Version: 2.0.0-rc1-snapshot.be55a0a
Date: 2021-12-03T11:09:57.266Z
CLI Version: 0.20.1 [abb21449]

## Additional context

[ originally reported by @per1234 ]

**Comment by per1234** [comment] 2022-03-10 04:01
The unexpected close bug that was the primary focus of this issue was fixed by https://github.com/arduino/arduino-ide/pull/791, but the fix was not very visible until https://github.com/arduino/arduino-ide/pull/880 due to a different "Save As..."-related regression introduced by https://github.com/arduino/arduino-ide/pull/791.

The loss of the unsaved changes bug is still not resolved, but will be tracked in a dedicated issue at https://github.com/arduino/arduino-ide/issues/896

**Closed by per1234** 2022-03-10 04:01 UTC
Labels: priority: high, topic: code, type: imperfection, criticality: medium
