### ISSUE TITLE
Open Example, Close, Open again - appears to open copy in %temp% directory

### ISSUE THREAD

**Issue by KurtE** [arduino/arduino-ide#1089] opened 2022-06-21 13:08 UTC
### Describe the problem

With the new nightly builds, it looks, like the code that remembers what sketch window that was last closed and tries to reopen it when you restart, it then looks like it reopens the example sketch, which is good.

However what it appears to remember is the directory within your temp directory

Now suppose in between the time you closed the Arduino IDE and reopened the IDE, your folder within temp is no longer there.
Could be you run a disk cleanup, or maybe your rebooted and your temp is on a Ram drive or ...

Now your Arduino IDE comes up in a strange state, something like:
![image](https://user-images.githubusercontent.com/1558080/174802173-087239fa-36c4-4363-b225-5df3e1bbae52.png)

Note: it does not show the example sketch.  Also in this case I had open the Sketchbook pane and it showed empty, but Files->Sketchbook does not show empty.

### To reproduce

Open an example Sketch.  In this case I opened MTP_Teensy->SD_MTP_debug  but I don't think that maters. 

Close the sketch: Ignore the error message (say no) about Save/Don't Save  #1026 

Clear out some of the folders within %temp% - like .arduinoIDE-unsaved*

Reopen the Arduino IDE

### Expected behavior

I would expect that it would reopen the example sketch.  Not the copy within the temp directory. 

And/Or - would detect that the folder was not found and maybe inform the user of it and recover.  Could either again go to the Example Sketch,  Could bring up empty sketch or ???

Again would be easier for user to recover from this if the hiccup if like IDE 1.x you update the Recent sketch list, to 
include the examples:  #935 

### Arduino IDE version

Daily build: 20220621

### Operating system

Windows

### Operating system version

Windows 10

### Additional context

Note: This is sort of a follow on and extension of my recent comments in #39 

In particular, have the example open, go away for a couple of hours with the sketch open.  
Have something like Norton running in background, which cleans up files.  Now it clears out the files within the 
.arduino... file in temp as the folder is in use so it can not delete it... 

You then come back to an empty IDE (no file shown) and cryptic message
![image](https://user-images.githubusercontent.com/1558080/174806078-23a3f32a-7007-45f7-bc09-b9b4cf8de25b.png)
Full image of window in 39... 

You then close the window and reopen and end up with similar to window I show in this issue,  except it knows that it could not open the sketch...
![image](https://user-images.githubusercontent.com/1558080/174806551-254d2dfc-4ab7-48b0-a7a0-9514de79d80d.png)

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-06-22 07:24
>Now your Arduino IDE comes up in a strange state

This can be reproduced via a simple procedure:

1. Close all but one Arduino IDE windows
   **ⓘ** This is done to simplify the demo because the IDE reopens all previous sketches on startup.
1. Select **File > Save As...** from the Arduino IDE menus.
1. Save the sketch to a convenient name and location.
1. Select **File > Quit** from the Arduino IDE menus.
1. Delete the sketch you saved in the previous step.
1. Start the Arduino IDE.

The Arduino IDE will be in that "strange" state where there is no editor.

I bisected this to 4c55807

I would prefer the behavior of Arduino IDE 1.8.19, where if the previous sketch can't be opened on startup, a new sketch is loaded.

**Closed** 2022-07-18 09:10 UTC
Labels: topic: code, type: imperfection
