### ISSUE TITLE
Arduino not throwing an error on an unusable serial port

### ISSUE THREAD

**Issue by robinwesterik** [arduino/arduino-ide#1957] opened 2023-03-14 07:36 UTC
### Describe the problem

I didn't have my permissions set correctly for my usb device. Arduino v1 would throw an error in these cases, notifying the user to fix their permissions. Arduino v2 doesn't throw any errors, and allows the user to try and send messages.

This is particularly confusing for linux users, as they don't have permissions to tty devices by default on most distros.

The only hint users get that their serial monitor is not behaving properly is the fact that they can't change the baud rate. Users might conclude the IDE isn't functioning properly, like I did.

### To reproduce

Set the port to something you don't have access to.
Open the Serial Monitor on a blank project and select a baud rate different from the default.

### Expected behavior

I expect to receive an error notifying me to fix my permissions

### Arduino IDE version

Version 2.0.4

### Operating system

Linux

### Operating system version

Arch Linux

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by kittaakos** [comment] 2023-03-14 12:54
Thank you for taking the time and reporting the problem. I think we have a ticket describing the issue: https://github.com/arduino/arduino-ide/issues/1508. We prefer keeping one open GH issue per defect, so I am closing this one as a duplicate. If you disagree, please ping me, and we can discuss and reopen it.

By the way, there is another upstream ticket to get the cause of the error and show it to the user: https://github.com/arduino/arduino-cli/issues/1767

**Closed by kittaakos** 2023-03-14 12:54 UTC
Labels: type: imperfection
