### ISSUE TITLE
Auto format only works on 'ino' files.

### ISSUE THREAD

**Issue by arnmulligan** [arduino/arduino-ide#83] opened 2020-10-22 23:11 UTC
Auto format only appears to work on _ino_ files; nothing happens when applied to _h_ or _cpp_ files.

Reproduce by opening an _h_ or _cpp_ file in a tab and selecting _auto format_.

Tested with following configuration:
arduino-pro-ide_nightly-20201022_Linux_64bit
Fedora 5.8.15-201.fc32.x86_64
Xfce4

**Comment by per1234** [comment] 2021-11-28 07:57
I was not able to reproduce this so I think it was fixed some time ago. There are still some problems with auto format reliability in general (https://github.com/arduino/arduino-ide/issues/396), but those affect `.ino` files just the same as `.h`/`.cpp` files, and will be greatly reduced by https://github.com/arduino/arduino-ide/pull/610

So I'll close this as fixed. If anyone is still able to reproduce the problem of auto format not doing anything on `.h`/`.cpp` files specifically, please comment here with details and I'll investigate.

**Closed by per1234** 2021-11-28 07:57 UTC
Labels: topic: language server, criticality: medium
