### ISSUE TITLE
Blank entries in boards selection Beta4

### ISSUE THREAD

**Issue by toogooda** [arduino/arduino-ide#250] opened 2021-03-21 01:51 UTC
**Describe the bug**
See attached image when you select a board for boards menu it shows multiple blank options with STM32 or ESP32 sub options. The standard AVR ones are completely missing

**To Reproduce**
1. Just look in boards under tools
Note: I have ESP32, MCUDUDE and STM32 cores installed for testing

**Expected behavior**
Display with text as per beta 3

**Screenshots**
![image](https://user-images.githubusercontent.com/9059644/111891036-20f8e300-8a54-11eb-8ede-8c5e2295ab8c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - IDE 2.0 beta4

**Comment by ubidefeo** [comment] 2021-03-22 07:44
Closed as duplicate of #244

**Closed by ubidefeo** 2021-03-22 07:44 UTC
Labels: type: bug
